---
driver:
  name: vagrant
  network:
    - ["private_network", {ip: "33.33.33.33"}]

provisioner:
  name: chef_zero
  always_update_cookbooks: true

verifier:
  name: inspec
  format: doc

platforms:
  - name: centos-7.2

suites:
  - name: default
    run_list:
      - recipe[rhcsa_rhce_study::default]
    attributes:
