name 'rhcsa_rhce_study'
maintainer 'David Coy'
maintainer_email 'david@obsidianspork.io'
license 'all_rights'
description 'Installs/Configures rhcsa_rhce_study'
long_description 'Installs/Configures rhcsa_rhce_study'
version '0.1.1'
